server:
  port: 9999
# Oracle Connect
spring:
  # File Size
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
   driver-class-name: oracle.jdbc.driver.OracleDriver
   url: jdbc:oracle:thin:@localhost:1521/xe
   username: scottJpa
   password: tiger
  
#gmail Trasfer
  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    properties: 
      mail:
        smtp: 
          auth: true
          starttls.enable: true
          
  # jpa Setting
  jpa:
   show-sql: true
   hibernate:
    ddl-auto: none
  
  # View Resolver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
      
# Mybatis  
mybatis:        # classpath : resource
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/*.xml #mappers폴더안에 어떠한 xml이든 허용하겠다
 
        
